server:
  port: 8760

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka